package tk.microdroid.blueirc;

public enum Event {
    CONNECTED, DISCONNECTED, TIMEOUT, UNKNOWN_HOST, UNKNOWN_ERROR,
    DATA_SEND_FAIL, DATA_RECEIVED, DATA_SENT, IRCV3_CAPABILITY_REJECTED,
    IRCV3_CAPABILITY_ACCEPTED, JOINED_CHANNEL, LEFT_CHANNEL, GOT_SERVER_NAME,
    GOT_MOTD, KICKED, FIRST_NICK_IN_USE, ALL_NICKS_IN_USE, LAG_MEASURED
}
